# Generated by Django 4.1.12 on 2024-03-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_first_name_profile_first_question_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('first_question_option', models.CharField(choices=[('hiking', 'Hiking'), ('water_sports', 'Water sports'), ('camping', 'Camping'), ('wildlife_s.exitafari', 'Wildlife Safari'), ('skating', 'Skating'), ('yoga_retreats', 'Yoga retreats'), ('sunset_seeker', 'Sunset seeker'), ('snow_boarding', 'Snow Boarding')], max_length=100)),
                ('second_question_option', models.CharField(choices=[('beach_destinations', 'Beach destinations'), ('mountains_nature_retreats', 'Mountains and Nature retreats'), ('urban_city_exploration', 'Urban City exploration'), ('historical_cultural_sites', 'Historical and cultural sites'), ('unique_cuisine', 'Anywhere with unique cuisine'), ('tropical_island', 'Tropical Island')], max_length=100)),
                ('third_question_option', models.CharField(choices=[('self_discovery', 'Self Discovery'), ('making_new_friends', 'Making New Friends'), ('learning_about_cultures', 'Learning About Different Cultures'), ('relaxation_reflection', 'Relaxation and Reflection'), ('self_discipline', 'Self Discipline'), ('practicing_meditation', 'Practicing Meditation')], max_length=100)),
                ('fourth_question_option', models.CharField(choices=[('backpacking', 'Backpacking'), ('surfing', 'Surfing'), ('marathons', 'Marathons'), ('food-cuisines', 'Food cuisines'), ('journalling', 'Journalling')], max_length=100)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
