# Generated by Django 4.1.12 on 2024-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_question_option',
            field=models.CharField(choices=[('hiking', 'Hiking'), ('water_sports', 'Water sports'), ('camping', 'Camping'), ('wildlife_s.exitafari', 'Wildlife Safari'), ('skating', 'Skating'), ('yoga_retreats', 'Yoga retreats'), ('sunset_seeker', 'Sunset seeker'), ('snow_boarding', 'Snow Boarding')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourth_question_option',
            field=models.CharField(choices=[('backpacking', 'Backpacking'), ('surfing', 'Surfing'), ('marathons', 'Marathons'), ('food-cuisines', 'Food cuisines'), ('journalling', 'Journalling')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_question_option',
            field=models.CharField(choices=[('beach_destinations', 'Beach destinations'), ('mountains_nature_retreats', 'Mountains and Nature retreats'), ('urban_city_exploration', 'Urban City exploration'), ('historical_cultural_sites', 'Historical and cultural sites'), ('unique_cuisine', 'Anywhere with unique cuisine'), ('tropical_island', 'Tropical Island')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_question_option',
            field=models.CharField(choices=[('self_discovery', 'Self Discovery'), ('making_new_friends', 'Making New Friends'), ('learning_about_cultures', 'Learning About Different Cultures'), ('relaxation_reflection', 'Relaxation and Reflection'), ('self_discipline', 'Self Discipline'), ('practicing_meditation', 'Practicing Meditation')], max_length=100, null=True),
        ),
    ]
