# Generated by Django 4.1.12 on 2024-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_followers_profile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_question_option',
            field=models.CharField(choices=[('hiking', 'Hiking'), ('water_sports', 'Water sports'), ('camping', 'Camping'), ('wildlife_safari', 'Wildlife Safari'), ('skating', 'Skating'), ('yoga_retreats', 'Yoga retreats'), ('sunset_seeker', 'Sunset seeker'), ('snow_boarding', 'Snow Boarding')], max_length=100, null=True),
        ),
    ]
