# Generated by Django 4.1.12 on 2024-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SB', 'Safety Basics'), ('DS', 'Destination-Specific Safety Guides'), ('EC', 'Emergency Contacts and Resources'), ('SG', 'Safety Gear and Gadgets'), ('TS', 'Transportation Safety Tips'), ('CS', 'Community Safety Stories')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
