# Generated by Django 4.1.12 on 2024-04-23 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safety_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyresource',
            name='likes',
            field=models.ManyToManyField(related_name='liked_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
