# Generated by Django 5.0.4 on 2024-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_resources', '0002_safetyresource_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyresource',
            name='card_img',
            field=models.ImageField(blank=True, default='static/images/SR1.png', null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='safetyresource',
            name='main_img',
            field=models.ImageField(blank=True, default='static/images/SR2.png', null=True, upload_to='static/images/'),
        ),
    ]
