# Generated by Django 4.1.12 on 2024-03-13 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('countryname', models.CharField(max_length=200)),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('rate_total', models.IntegerField(blank=True, default=0, null=True)),
                ('rate_average', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
