# Generated by Django 4.1.12 on 2024-03-16 22:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='main_img',
            field=models.ImageField(blank=True, default='static/images/destinations/alps.png', null=True, upload_to='static/images/profiles/'),
        ),
        migrations.AddField(
            model_name='city',
            name='venture1_img',
            field=models.ImageField(blank=True, default='static/images/destinations/chapel.png', null=True, upload_to='static/images/destinations/'),
        ),
        migrations.AddField(
            model_name='city',
            name='venture2_img',
            field=models.ImageField(blank=True, default='static/images/destinations/tour.png', null=True, upload_to='static/images/destinations/'),
        ),
        migrations.AddField(
            model_name='city',
            name='venture3_img',
            field=models.ImageField(blank=True, default='static/images/destinations/view.png', null=True, upload_to='static/images/destinations/'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('★☆☆☆☆', '1 Star'), ('★★☆☆☆', '2 Star'), ('★★★☆☆', '3 Star'), ('★★★★☆', '4 Star'), ('★★★★★', '5 Star')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.city')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('owner', 'city')},
            },
        ),
    ]
