# Generated by Django 4.1.12 on 2024-03-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_city_main_img_city_venture1_img_city_venture2_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='rate_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.FloatField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1),
        ),
    ]
