# Generated by Django 4.1.12 on 2024-04-04 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_city_rate_average_alter_review_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='venture1_img',
        ),
        migrations.RemoveField(
            model_name='city',
            name='venture2_img',
        ),
        migrations.RemoveField(
            model_name='city',
            name='venture3_img',
        ),
        migrations.AddField(
            model_name='city',
            name='card_img',
            field=models.ImageField(blank=True, default='static/images/destinations/luc2.png', null=True, upload_to='static/images/destinations/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='main_img',
            field=models.ImageField(blank=True, default='static/images/destinations/alps.png', null=True, upload_to='static/images/destinations/'),
        ),
        migrations.CreateModel(
            name='Ventures',
            fields=[
                ('title', models.CharField(blank=True, default='Coming Soon', max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('venture_img', models.ImageField(blank=True, default='static/images/destinations/defaultvent.png', null=True, upload_to='static/images/destinations/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.city')),
            ],
        ),
    ]
